
export const DELETEEMPLOYEES = "DELETEEMPLOYEES";
export const UPDATEEMPLOYEES = "UPDATEEMPLOYEES";
export const NEWUPDATEEMPLOYEES = "NEWUPDATEEMPLOYEES";
export const ADDEMPLOYEES1 = "ADDEMPLOYEES1";